language: cpp
sudo: required
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=2.7
         CUDA_VERSION="9.1.85_387.26"
  - os: linux
    env: PYTHON=3.4
         CUDA_VERSION="9.1.85_387.26"
  - os: osx
    env: PYTHON=2.7
         CUDA_VERSION="9.1.128"
  - os: osx
    env: PYTHON=3.6
         CUDA_VERSION="9.1.128"
before_install:
- |
  if [ "${PYTHON:0:1}" = "2" ]; then
    export PY=python2
    export PIP=pip2
    export PYNVML=nvidia-ml-py
  elif [ "${PYTHON:0:1}" = "3" ]; then
    export PY=python3
    export PIP=pip3
    export PYNVML=nvidia-ml-py3
  fi

  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    export CXX=g++-4.8
    export CC=gcc-4.8
    source ./script/install-cuda-trusty.sh
    if [ "${PYTHON:0:1}" = "3" ]; then sudo apt-get install python$PYTHON python3-pip; fi
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    source ./script/install-cuda-osx.sh
  fi

  ${PIP} install --user --disable-pip-version-check --no-warn-script-location --upgrade pip virtualenv

  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    echo $PATH | grep -q "/Users/travis/Library/Python/$PYTHON/bin"
    if [ $? -eq 0 ]; then
      export PATH="/Users/travis/Library/Python/$PYTHON/bin:$PATH"
    fi
  fi

  virtualenv -p python$PYTHON venv$PYTHON
  source venv$PYTHON/bin/activate
  ${PIP} install --upgrade pytest
  ${PIP} install --upgrade $PYNVML
install:
- |
  ${PY} setup.py install
script:
- |
  ${PY} -m pytest tests/test.py
